version: '2.1'

services:
  cartoons-backend:
    image: cartoons-backend
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3003:3003
      - 9229:9229
    ## set your startup file here
    command: node --inspect app.js